version: '3'
services:
  db:
     build: ./database
     container_name: shoppingcart_db
     volumes:
       - ./database/volume:/var/lib/mysql
     restart: always
     ports:
        - "3306:3306"
     environment:
       MYSQL_ROOT_PASSWORD: admin
       MYSQL_DATABASE: shoppingCart
       MYSQL_USER: admin
       MYSQL_PASSWORD: admin

